########################
# MONITOR SETUP
########################
monitor=,preferred,auto,1

$terminal = ghostty

########################
# AUTOSTART
########################
exec-once = hyprpaper 
exec-once = dunst
exec-once = waybar
exec-once = nm-applet
#exec-once = gnome-terminal
exec-once = wl-paste --type text --watch cliphist store
exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


########################
# GENERAL SETTINGS
########################
general {
  gaps_in = 5
  gaps_out = 10
  border_size = 2
  col.active_border = rgba(ffffffff)
  col.inactive_border = rgba(595959aa)
  layout = dwindle
}

########################
# DECORATIONS
########################
#decoration {
#  rounding = 10
  #blur {
    #enabled = true
   # size = 5
  #  passes = 3
 # }
  #drop_shadow = true
  #shadow_range = 4
  #shadow_render_power = 3
  #col.shadow = rgba(00000044)
#}

########################
# INPUT SETTINGS
########################
input {
  kb_layout = us, th
  follow_mouse = 0
  kb_options = grp:win_space_toggle,caps:ctrl_modifier
  touchpad {
    natural_scroll = true
  }
}

########################
# KEY BINDINGS
########################
$mod = SUPER

# screenshort 
bind = $mod, S, exec, grim ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png && pw-play /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
bind = $mod SHIFT, S, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png && pw-play /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
bind = $mod CTRL, S, exec, grim -g "$(slurp)" - | swappy -f - && pw-play /usr/share/sounds/freedesktop/stereo/camera-shutter.oga
bind = $mod CTRL SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy && pw-play /usr/share/sounds/freedesktop/stereo/camera-shutter.oga

bind = $mod, RETURN, exec, $terminal
bind = $mod, Q, killactive,
bind = $mod, E, exec, nautilus # onpe file discrover 
bind = $mod, D, exec, wofi --show drun # show list of application
bind = $mod, F, fullscreen,
bind = $mod, V, togglefloating,
bind = $mod, ESCAPE, exit,
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d
bind = ALT, TAB, cyclenext,
bind = ALT SHIFT, TAB, cyclenext,
bind = $mod, TAB, focuscurrentorlast,
bind = $mod SHIFT, L, exec, hyprlock
bind = $mod, C, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
# sound control
bind = $mod, P, exec, pavucontrol
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t

# blue connected 
bind = $mod, B, exec, blueman-manager

# Window movement
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

########################
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7


########################
# LAYOUTS
########################
dwindle {
  pseudotile = true
  preserve_split = true
}

#master {
#  new_is_master = true
#}

########################
# ANIMATIONS
########################
animations {
  enabled = true
  bezier = easeOut, 0.25, 1, 0.5, 1
  animation = windows, 1, 3, easeOut
  animation = border, 1, 10, default
  animation = fade, 1, 10, easeOut
  animation = workspaces, 1, 6, easeOut
}

########################
# MISC
########################
misc {
  disable_hyprland_logo = false 
  mouse_move_enables_dpms = false 
  enable_swallow = false 
}

