background {
    monitor =
    path = # path of image
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.15
}


############################
# CLOCK
############################

label {
    monitor = eDP-1
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(ffffffff)
    font_size = 80
    font_family = Sans
    position = 0, 200
    halign = center
    valign = center
}

############################
# DATE
############################

label {
    monitor = eDP-1
    text = cmd[update:60000] echo "$(date +'%A, %d %B %Y')"
    color = rgba(ddddddff)
    font_size = 25
    font_family = Sans
    position = 0, 130
    halign = center
    valign = center
}

############################
# PASSWORD FIELD
############################

input-field {
    monitor = eDP-1
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(ffffffff)
    inner_color = rgba(000000aa)
    font_color = rgba(ffffffff)
    fade_on_empty = false
    rounding = 10
    position = 0, -100
    halign = center
    valign = center
    placeholder_text = <i>just type password bro</i>
    }
