input {
  kb_layout = us, th
  # Toggle US/TH with Win+Space; use Caps Lock as an extra Ctrl
  kb_options = grp:win_space_toggle,caps:ctrl_modifier
  follow_mouse = 0
  touchpad {
    natural_scroll = true
  }
}
